### PR TITLE
remove splash msg

### PR DESCRIPTION
**Pull request by dradetsky**
Apart from anything else, when I first started playing with beamcoder to try to figure it out, these messages made it harder to read the errors.

### CODE REVIEW

**Comment by sparkpunkd** [comment]
The splash message is mandated in the GPL license term and conditions. It cannot be removed.

**Comment by dradetsky** [comment]
@sparkpunkd I do not think you are right about that. The mere fact that so many projects which come from the FSF and similar do not do this ought to make you realize that it probably is not required.

In any case, do you _want_ to remove it? Or do you _want_ to keep it in? Or do you not care either way, you just don't want to violate the GPL?

**Comment by dradetsky** [comment]
@scriptorian opinion?

**Comment by scriptorian** [comment]
I believe the splash message is "Appropriate Legal Notices" as described in the [license agreement](https://www.gnu.org/licenses/gpl-3.0.html) and should stay.

**Comment by dradetsky** [comment]
@scriptorian @sparkpunkd I asked you both whether or not you *wanted* the notices for a reason. Whether or not the notices are required is a factual question on which you could seek expert guidance. For example, the FSF employs lawyers who might be willing to help you answer this question.

I made the PR to attempt to make beamcoder, in my opinion, better and more useful as a piece of technology. Without these messages, it's easier for me to use the library to solve my problems. If you agree with this, but are worried about the legal implications, that's totally understandable. It also tells us how to proceed. We figure out the actual legal implications, and try to solve the problem within the boundaries of what they permit.

If on the other hand, you *don't* agree, and you *want* the notices, then the requirements of the GPL are neither here nor there. It's your project, and you don't want this PR. You consider the ways in which it would improve my personal UX a non-goal for your project. That's your privilege.

So rather than disagree about what is or isn't required by the GPL, let me ask: do you approve of the goal or not?

**Pull request closed without merging**
